### ISSUE TITLE
Question regarding bch on GF(4)

### ISSUE THREAD

**Issue by nicolas-f** [mborgerding/bch_codec#1]
Hi,

I'm not yet used to coding therory.

I'm developing a library to transfer data through audio signals ("long" range air gaped devices)

https://github.com/ifsttar/openwarble

Each audio pitch are placed on 16 different audio frequency. But with the background noise the library may miss the pitch. So a Byte is composed by two pitch.

The Reed-Solomon code RS(18, 10) shortened from an RS(255,223) is currently used but the symbol is 8 bits and not 4 bits. So if I miss only a pitch, the entire Byte is lost.

Related Stack Exchange question

https://math.stackexchange.com/questions/2965782/error-correcting-code-for-hexadecimal-symbol

With your BCH codec implementation, can I use 4-bit symbols ?

Thanks

**Comment by mborgerding** [comment]
Neat concept.  

I'm afraid the `bch_codec` code might take quite a bit of work to adapt to word sizes other than 8 bits.

**Comment by mborgerding** [comment]
Do you really  need to use 16 different tones?  Why not use a mixture of 8 independent tones?  This would transmit a byte at a time instead of 4 bits.

**Comment by nicolas-f** [comment]
Currently I mix 2 tones, on 32 frequencies. But In my test, this is exclusively only one tone that are missed.

**Comment by nicolas-f** [comment]
After some thinking I think you are right. I could run convolution over 14 frequencies at each symbol

- using 2*Hamming (7,4) 
- using additional BCH for correcting Bytes

What do you think ?

**Comment by mborgerding** [comment]
I think dsp.stackexchange.com might be able to give you some useful input.
